### ISSUE TITLE
Plugin Not Recognized By Terraform

### ISSUE THREAD

**Issue by AMcManigal** [anasinnyk/terraform-provider-1password#11]
HI Team,

Thanks for making this provider! Unfortunately I can't get this working with Terraform 0.12.1. I have downloaded v0.30.0 of your plugin (Darwin) and added it to ~/.terraform.d/plugins/darwin_amd64. I'm on Mac OS Mojave 10.14.5.

I have added the following provider instantiation from your example expecting it to fail due to bad creds.

```
provider "onepassword" {
    email      = "john.smith@example.com"
    password   = "super secret master password"
    secret_key = "A3-XXXXXX-XXXXXXX-XXXXX-XXXXX-XXXXX-XXXXX"
    subdomain  = "company"
}
```

However when I try `terraform init` I get the following error.
```Provider "onepassword" not available for installation.```

I have the [ALKS](https://github.com/Cox-Automotive/terraform-provider-alks) provider installed in the same directory and it is recognized as expected, so I don't think it's something on my side.

Thanks,
Adam

**Comment by AMcManigal** [comment]
I figured it out. The default name for your release artifacts causes terraform to not recognize it as a provider. Changing the name to terraform-provider-onepassword_v0.3.0 for the latest release fixed the problem.

**Comment by anasinnyk** [comment]
@AMcManigal thank for open this issue. I will reconfigure travis build and after that situation should be better. Thanks.

**Comment by anasinnyk** [comment]
feel free to re-open this issue if something went wrong
