### ISSUE TITLE
Can't run Darwin binary on Catalina

### ISSUE THREAD

**Issue by kylelundstedt** [anasinnyk/terraform-provider-1password#16]
Thanks for the awesome TF provider for 1Password!  Just an FYI, the Darwin binary works fine on previous macOS versions.  However, if you use the 10.15 (Catalina) Beta, the Darwin binary won't run.

Specifically, upon running `terraform plan`, a pop-up message appears saying:
 "terraform-provider-onepassword_v0.4.1" can't be opened because its integrity cannot be verified```
The only options are "Move to Trash" or "Cancel".

Your filename makes clear that the binary is 64 bit.  Perhaps it involves [notarization](https://eclecticlight.co/2019/06/07/notarization-in-mojave-and-catalina/)?  I tried to find a workaround, but to no avail.

**Comment by anasinnyk** [comment]
Hi @kylelundstedt, thanks for the interesting of project.
I don't have Catalina, and I think it's not a good idea because my binary download latest 1password-cli binary and I cannot control notarization for that. You can try to install this binary via golang. Lime `GO111MODULE=on go install github.com/anasinnyk/terraform-provider-1password`.
After that move to your terraform directory `mv $GOPATH/bin/terraform-provider-1password path/to/your/module/.terraform/plugins/darwin_amd64/terraform-provider-onepassword_v0.4.1`

**Comment by kylelundstedt** [comment]
Hi @anasinnyk, 

Thanks for the quick response!
I did try your suggestion; no luck. Because `terraform-provider-onepassword_v0.4.1` is a binary file, Catalina checks that binary to see if it's verified regardless of how it is downloaded to the system.
I also tried building from source, but no joy either.  Bummer.

**Comment by kylelundstedt** [comment]
Hi @anasinnyk 

Here's more info on what's required from you as a developer in order for your users to use your `terraform-provider-1password` plugin on macOS 10.15 beta and beyond:

https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

And here's a workaround for the interim:

https://www.imore.com/how-open-apps-unidentified-developers-mac

**Comment by anasinnyk** [comment]
@kylelundstedt hi, can you check 0.5.0 version on catalina?
This bug fixed in golang https://github.com/golang/go/issues/32673 maybe that's help. 
Thanks

**Comment by kylelundstedt** [comment]
No joy, @anasinnyk.

I get the same pop-up: 
```
“terraform-provider-onepassword_v0.5.0” can’t be opened because its integrity cannot be verified.
```

**Comment by anasinnyk** [comment]
https://github.com/microsoft/vscode/issues/74782 - you can use it like this :)

**Comment by kylelundstedt** [comment]
👍👍👍
