### ISSUE TITLE
Feature - Group resources

### ISSUE THREAD

**Issue by taiidani** [anasinnyk/terraform-provider-1password#18]
**Is your feature request related to a problem? Please describe.**

Considering using this provider for our team/user management system, which is configured using Terraform.

**Describe the solution you'd like**

A `onepassword_group` resource from the "Manage Access" section of the docs: https://support.1password.com/command-line/#manage-access.

**Describe alternatives you've considered**

We currently perform this act manually, while our GitHub, AWS, and other systems are successfully Terraformed.

**Additional context**

I'd be happy to take this request on if the repository maintainer welcomes Pull Requests!

**Comment by anasinnyk** [comment]
Hi, thanks for your ticket.
I had this functionality previously, but I don't have 1password account which can manage users and groups and I cannot check it. If you can create pull request it will be awesome.

> We currently perform this act manually, while our GitHub, AWS, and other systems are successfully Terraformed.

Good idea, we have a really similar solution.
