### ISSUE TITLE
Add to Community Providers

### ISSUE THREAD

**Issue by julianxhokaxhiu** [anasinnyk/terraform-provider-1password#21]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add this provider to the community list, in order to ease the installation.

**Describe alternatives you've considered**
Manual steps in the README of the project.

**Additional context**
See https://www.terraform.io/docs/providers/type/community-index.html

**Comment by anasinnyk** [comment]
@julianxhokaxhiu it's already in the list. In the first place :)

**Comment by julianxhokaxhiu** [comment]
Sorry, I totally missed it! Thank you!

**Comment by julianxhokaxhiu** [comment]
I was actually too fast. If I delete the provider plugin installed into my local environment and I run my terraform code, I get this:
```
Provider "onepassword" not available for installation.

A provider named "onepassword" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".
```

Any idea why?

**Comment by anasinnyk** [comment]
@julianxhokaxhiu only official providers included to the registry

**Comment by julianxhokaxhiu** [comment]
Allright, I see. Thanks than.

**Comment by vikram-yerneni** [comment]
Hi @julianxhokaxhiu ,
How did you sorted out this issue? I am having the same here.
My Terraform Init is failing with the same error

Thanks
Vikram
