### ISSUE TITLE
Error: open /tmp/op_0.5.5.zip: The system cannot find the path specified.

### ISSUE THREAD

**Issue by kennedy** [anasinnyk/terraform-provider-1password#24]
Platform:
Windows10 Pro. 
Terraform v0.12.12
provider.onepassword v0.5.0

I downloaded the release directly from [here ](https://github.com/anasinnyk/terraform-provider-1password/releases/tag/0.5.0) *latest as of this writing. I put it directly into `.terraform\plugins\windows_amd64\terraform-provider-onepassword_v0.5.0`

Here is a snippet of main.tf:
```HCL
provider "onepassword" {
  subdomain = "myorg"
}

data "onepassword_vault" "myvault"{
  name = "rando_vault"
}
```

Here is my error.
```
Error: open /tmp/op_0.5.5.zip: The system cannot find the path specified.

  on main.tf line 1, in provider "onepassword":
  1: provider "onepassword" {
```
I thought maybe the executable filename was the issue, so I bumped it manually to 0.5.5. Did not resolve the issue.

**Comment by anasinnyk** [comment]
Hi @kennedy 
Sorry for so late response. I think it's a really incorrect name. Please try to rename it on `terraform-provider-onepassword_v0.5.0.exe` I cannot check it because I don't have a Windows system : )

**Comment by kennedy** [comment]
Hello @anasinnyk it seems `terraform-provider-onepassword_v0.5.0.exe` gives me the same error. I will investigate a bit more

**Comment by EamonHetherton** [comment]
I encountered this yesterday.  

The problem is that the provider tries to download the cli tool to the absolute path "/tmp/" which may be a viable location under linux but does not exist by default in windows.  I created a c:\tmp folder and was able to move past it, but I'd suggest that the provider finds the temp location from environment variables instead.

**Comment by anasinnyk** [comment]
@EamonHetherton thank you. I try to change code for this case.

**Comment by kennedy** [comment]
> I encountered this yesterday.
> 
> The problem is that the provider tries to download the cli tool to the absolute path "/tmp/" which may be a viable location under linux but does not exist by default in windows. I created a c:\tmp folder and was able to move past it, but I'd suggest that the provider finds the temp location from environment variables instead.

This solved my issue! thanks

**Comment by ibauersachs** [comment]
@anasinnyk This is still an issue in v1.2.1.
