### ISSUE TITLE
the '--raw' parameter is unsupported since v.0.9.4 or earlier

### ISSUE THREAD

**Issue by overratedpro** [anasinnyk/terraform-provider-1password#34]
Hi, thanks for doing the good work!

I have a problem to report regarding this version checking call with latest `op` CLI versions for Mac:
https://github.com/anasinnyk/terraform-provider-1password/blob/d16ba4384601a0f68f2b5eaafeb496e6072c0b29/onepassword/provider.go#L157

My observation is that using an `OP_VERSION` env var has no longer an effect due to the parameter `--raw` which is apparently no longer supported, which in turn makes the provider enter the `installOPClient` routine.

Tested with Mac `op` versions:
- 0.9.4
- 0.10.0 (latest as of now)

Running `op --version --raw` has this effect:
```
$ op --version --raw
[LOG] 2020/05/13 18:23:27 (ERROR)  unknown flag: --raw
Usage:
  op [command]
...
```

**Comment by anasinnyk** [comment]
Thanks for your request. I removed it.
