### ISSUE TITLE
Publish provider for use in Terraform 0.13

### ISSUE THREAD

**Issue by aicarmic** [anasinnyk/terraform-provider-1password#39]
👋 Hi, I'm on the Terraform Providers team at HashiCorp. With the release of the Terraform 0.13 beta, users can now download and install community providers from the registry. We are inviting provider authors (especially those for popular community providers) to publish their providers in a closed beta.

To get invited to the closed beta, please email terraform-registry-beta@hashicorp.com. We need:

- A list of GitHub usernames to add to the beta (you and any team members who will publish)
- List of provider repositories you plan to publish
- A GPG public key in ASCII-armor format, which you will be using to sign your provider releases

You can use one key for all of your providers, or separate keys if you prefer. If you are publishing from an organization, this key or keys will be associated with that namespace. Once in the beta, you can manage personal keys in the UI as well.

**Comment by Dniwdeus** [comment]
@anasinnyk Do you need any help to apply for the new Terraform registry?
I need to update our company's stack to Terraform 0.13 and yours is the only provider from our stack missing in the new registry ... I won't be able to postpone the transfer any longer and I really need your provider in the registry, so let me know if I can do anything to speed things up for you. :wink:

**Comment by aicarmic** [comment]
As of 8/10/2020, provider publishing is now generally available to anyone in our community, so that should hopefully make this smooth! All the steps are [outlined in our docs](https://www.terraform.io/docs/registry/providers/publishing.html).

**Comment by Dniwdeus** [comment]
https://registry.terraform.io/providers/milosbackonja/1password/latest/docs
thx guys! awesome!
:tada: :balloon: :fireworks: :grin:

**Comment by mcmarkj** [comment]
Anyone else facing this issue? Not sure why it's specifying hashicorp/onepassword when in my versions.tf I've specifically put milosbackonja/1password

<img width="334" alt="Screenshot 2020-11-04 at 17 34 03" src="https://user-images.githubusercontent.com/8041254/98225472-a5871100-1f4c-11eb-9549-349b1d02bb19.png">

**Comment by adrian-catana** [comment]
> Anyone else facing this issue? Not sure why it's specifying hashicorp/onepassword when in my versions.tf I've specifically put milosbackonja/1password
> 
> <img alt="Screenshot 2020-11-04 at 17 34 03" width="334" src="https://user-images.githubusercontent.com/8041254/98225472-a5871100-1f4c-11eb-9549-349b1d02bb19.png">

I have a similar problem, it seams to me onepassword was uploaded to https://registry.terraform.io with the wrong name of "1password" instead of "onepassword", in https://registry.terraform.io/providers/milosbackonja/1password/latest/docs if you click on "Use provider" we get this instruction:

```
terraform {
  required_providers {
    1password = {
      source = "milosbackonja/1password"
      version = "1.1.0"
    }
  }
}

provider "1password" {
  # Configuration options
}
```

this is wrong since required_providers keys can't start with a number, the same with all resouces and data sources:

```
1password_group
1password_group_member
1password_item_common
1password_item_credit_card
1password_item_document
1password_item_identity
....
```

this not correct, a name must start with a letter or underscore not '1'.

**Comment by adrian-catana** [comment]
I got it to partialy work like this:

```
terraform {
  required_providers {
    onepassword= {
      source = "milosbackonja/1password"
      version = "1.1.0"
    }
  }
}

provider "onepassword" {
  subdomain = var.domain
}

data "onepassword_vault" "vault" {
  provider = onepassword
  name = var.vault_name
}
```

- Please note that if you use onepassword inside a module you need to set the required_providers inside that module or else it will try load it from hashicorp/onepassword and fail
- The subdomain is ignored in above example, this is why it's only partially working (it does work with OP_SUBDOMAIN env variable)
- you need to specifically set the provider in each data/resource

**Comment by aicarmic** [comment]
This is likely the result of Terraform not currently supporting resources/blocks containing numbers. Terraform will default to searching for the provider in the `hashicorp/...` namespace if a valid one is not specified. If you configure your `required_providers` as @adrian-catana suggests, it should work (see below). We are looking into ways to address this scenario.

```
terraform {
  required_providers {
    onepassword = {
      source  = "milosbackonja/1password"
      version = "1.1.0"
    }
  }
}
```

**Comment by throwaway8787** [comment]
@aicarmic what's to stop someone from uploading their own version of this, so it automatically downloads from the registry, fetches folks passwords, and uploads them to an intermediary server?

**Comment by throwaway8787** [comment]
@Dniwdeus - did you make a PR?

**Comment by anasinnyk** [comment]
https://registry.terraform.io/providers/anasinnyk/onepassword/latest - I published my own. If it fixed this issue please let me know. Thx.

**Comment by anasinnyk** [comment]
@Dniwdeus thanks for your job. If you can create some PR for fixing some issues about TF 0.13 or any other please feel free. ![](https://media2.giphy.com/media/osjgQPWRx3cac/giphy.gif)

**Comment by aicarmic** [comment]
> @aicarmic what's to stop someone from uploading their own version of this, so it automatically downloads from the registry, fetches folks passwords, and uploads them to an intermediary server?

@throwaway8787 It has always been possible to distribute and install any Provider, though the registry intentionally makes this easier.  Our [official and verified tiers](https://www.terraform.io/docs/registry/providers/index.html#provider-tiers-amp-namespaces) help users make an informed decision, as either HashiCorp or a verified third-party is behind the integration. As with every package manager, the user ultimately assumes responsibility for the dependencies they include. More details on this are included in our [terms of use](https://registry.terraform.io/terms).

**Comment by aicarmic** [comment]
> https://registry.terraform.io/providers/anasinnyk/onepassword/latest - I published my own. If it fixed this issue please let me know. Thx.

@anasinnyk Working well here! 
![image](https://user-images.githubusercontent.com/1105554/99003289-1b661c00-24fb-11eb-9b7c-2bea83cabbcc.png)

**Comment by anasinnyk** [comment]
Thanks @aicarmic
