### ISSUE TITLE
Invite to the new Terraform Registry

### ISSUE THREAD

**Issue by aicarmic** [anasinnyk/terraform-provider-1password#51]
**Is your feature request related to a problem? Please describe.**
Improved discovery and simplified installation with Terraform 0.13

**Describe the solution you'd like**
Hi there, we noticed this provider is on our list of community providers, however it has not yet been published to the newly-released Terraform Registry for Providers. We'd like to invite you to get it published. Instructions for doing so are available [here](https://www.terraform.io/docs/registry/providers/publishing.html). Please note that we will soon be redirecting the [community listing page](https://www.terraform.io/docs/providers/type/community-index.html) to registry.terraform.io. 

Thanks for your contributions and we look forward to seeing the 1Password provider listed soon!

Thanks,
Team Terraform @ HashiCorp

**Comment by aicarmic** [comment]
One other note...if you need some help creating documentation, take a look at [this project](https://github.com/hashicorp/terraform-plugin-docs) which may come in handy!

**Comment by throwaway8787** [comment]
Dupe of #39, no?
