### ISSUE TITLE
I get an error when running terraform plan.

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [anasinnyk/terraform-provider-1password#52]
After installing the provider and running the execution, I get the following error, can you tell me how can I solve it?
Tried my OP_version version below, the error was similar.
export OP_version = 0.7.1
```
Error: Cannot signin: 
Exit code: fork/exec /tmp/terraform-provider-onepassword/0.7.1/op: no such file or directory
```

Default
```
Error: Cannot signin: 
Exit code: fork/exec /tmp/terraform-provider-onepassword/1.4.0/op: no such file or directory
```

**Comment by anasinnyk** [comment]
this code must download correct version for you to /tmp directory.

**Comment by IlyaNakhaichuk** [comment]
@anasinnyk By default, the provider could not do this. I solved this problem by putting it separately. op cli, only after that, the provider started working and the error disappeared.
