### ISSUE TITLE
Assign Groups to Vaults

### ISSUE THREAD

**Issue by lleifermann** [anasinnyk/terraform-provider-1password#53]
**Is your feature request related to a problem? Please describe.**
We are currently evaluating if we can use 1password with this provider. While looking through the documentation, i noticed that there seems to be not way to assign a Group to a Vault. However it is possible to assign Accounts to Groups -> https://github.com/anasinnyk/terraform-provider-1password/issues/44

Is there something i am missing here? 

**Describe the solution you'd like**
A ressource that accepts a groupname and a vaultname and assigns the given Group to the Vault

**Comment by tillepille** [comment]
I would go further and would say it would be great to have a resource `vault_membership` resource which takes a vault and either a `onepassword_group` or `onepassword_user` as input. As far as I can see the CLI supports this.
