### ISSUE TITLE
Invalid resource type

### ISSUE THREAD

**Issue by ms32035** [anasinnyk/terraform-provider-1password#54]
Getting the following error when running the registry build https://registry.terraform.io/providers/milosbackonja/1password/latest with TF 0.13

```
2020/10/26 11:25:22 [ERROR] eval: *terraform.EvalValidateResource, err: Invalid resource type: A data resource type "onepassword_vault" is not supported by provider "registry.terraform.io/hashicorp/1password".
2020/10/26 11:25:22 [ERROR] eval: *terraform.EvalSequence, err: Invalid resource type: A data resource type "onepassword_vault" is not supported by provider "registry.terraform.io/hashicorp/1password".
```

Might seem like a namespacing issue, but not sure. Any ideas?

**Comment by anasinnyk** [comment]
I published my own. Please try againg with it. https://registry.terraform.io/providers/anasinnyk/onepassword/latest

**Comment by ms32035** [comment]
That now works well. Thanks.
