### ISSUE TITLE
Publish in the Terraform registry

### ISSUE THREAD

**Issue by oscarmorasu** [anasinnyk/terraform-provider-1password#61]
Do you have plans to publish this provider in the TF registry? 

Currently there's [this one](https://registry.terraform.io/providers/milosbackonja/1password/latest), which is a fork of this repo

**Comment by oxr463** [comment]
Isn't that already here? https://registry.terraform.io/providers/anasinnyk/onepassword/1.2.1

**Comment by anasinnyk** [comment]
Yes, it is
